<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://endpoint.web.api.games.betfair.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://www.betfair.com/serviceapi/v1.0/PartnerAPI/" name="PartnerAPIServiceImplService" targetNamespace="http://endpoint.web.api.games.betfair.com/">
  <wsdl:import location="file:./pp-gap-client/src/main/resources/PP-PartnerApi_Port.wsdl" namespace="http://www.betfair.com/serviceapi/v1.0/PartnerAPI/">
    </wsdl:import>
  <wsdl:binding name="PartnerAPIServiceImplServiceSoapBinding" type="ns1:PartnerAPIService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="retrieveBalance">
      <soap:operation soapAction="retrieveBalance" style="document"/>
      <wsdl:input name="retrieveBalance">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="retrieveBalanceResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="PartnerAPIExceptionFault">
        <soap:fault name="PartnerAPIExceptionFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="keepAlive">
      <soap:operation soapAction="keepAlive" style="document"/>
      <wsdl:input name="keepAlive">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="keepAliveResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="PartnerAPIExceptionFault">
        <soap:fault name="PartnerAPIExceptionFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="transfer">
      <soap:operation soapAction="transfer" style="document"/>
      <wsdl:input name="transfer">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="transferResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="PartnerAPIExceptionFault">
        <soap:fault name="PartnerAPIExceptionFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="cancelTransfer">
      <soap:operation soapAction="cancelTransfer" style="document"/>
      <wsdl:input name="cancelTransfer">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="cancelTransferResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="PartnerAPIExceptionFault">
        <soap:fault name="PartnerAPIExceptionFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="retrieveUserSessionDetails">
      <soap:operation soapAction="retrieveUserSessionDetails" style="document"/>
      <wsdl:input name="retrieveUserSessionDetails">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="retrieveUserSessionDetailsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="PartnerAPIExceptionFault">
        <soap:fault name="PartnerAPIExceptionFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PartnerAPIServiceImplService">
    <wsdl:port binding="tns:PartnerAPIServiceImplServiceSoapBinding" name="PartnerAPIServiceImplPort">
      <soap:address location="http://gappp.prd.internal/gamesapi/service/PartnerAPI"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
